language:
  - node_js
node_js:
   - 11
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
install:
 - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
 - git fetch --tags --depth=10000
 - npm install
script:
 - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_success:
 - git remote add upstream "https://${GH_TOKEN}@github.com/${GH_REPO}.git"
 - npm version patch -m "[ci skip] version bumped %s"
 - npm run build:config
 - git add .
 - git commit -m "[ci skip] version ok"
 - git push upstream HEAD:master
 - npm run build:app
deploy:
  local_dir: www
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  fqdn: radartorain.com
  on:
    branch: master
env:
  global:
    - GH_REPO: "raainio/radartorain"
